Vagrant.configure("2") do |config|
  
  config.vm.define "windows" do |windows|
    windows.vm.box = "kiamol/windows-2019"
    windows.vm.hostname = "windows"
    windows.vm.network "private_network", type: "dhcp"

    windows.vm.guest = "windows"    
    windows.vm.communicator = "winrm"

    windows.vm.provision "shell", path: "setup.ps1", powershell_elevated_interactive: true, reboot: true

    windows.vm.provider :hyperv do |v|
      v.vmname = "windows"
      v.maxmemory = 3000
      v.cpus = 1
    end
    
    windows.vm.provider :virtualbox do |v|
      v.name = "windows"
      v.memory = 3000
      v.cpus = 1
    end
  end

  
  config.vm.define "lcow" do |lcow|
    lcow.vm.box = "kiamol/windows-2019"
    lcow.vm.hostname = "lcow"
    lcow.vm.network "private_network", type: "dhcp"

    lcow.vm.guest = "windows"    
    lcow.vm.communicator = "winrm"

    lcow.vm.provision "shell", path: "setup-lcow.ps1", powershell_elevated_interactive: true, reboot: true

    lcow.vm.provider :hyperv do |v|
      v.vmname = "lcow"
      v.maxmemory = 3000
      v.cpus = 1
      v.enable_virtualization_extensions = true
    end
    
    lcow.vm.provider :virtualbox do |v|
      v.name = "lcow"
      v.memory = 3000
      v.cpus = 1
    end
  end

end